export const REACT_DESIGN_META = {
  id: "react-feedback-survey",
  name: "React Ecosystem & Developer Pain Points",
  shortName: "React Ecosystem Survey",
  category: "Engineering & Frontend",
  badge: "React 19",
  description:
    "A 3-level branching DAG survey uncovering specific React & frontend developer pain points, architecture choices, and tooling preferences.",
  theme: {
    accentColor: "#00D8FF",
    badgeColor: "bg-cyan-500/10 text-cyan-400 border-cyan-500/20",
  },
}

export const REACT_FORM_DESIGN = {
  id: "react-feedback-survey",
  title: "React Ecosystem & Developer Pain Points",
  description:
    "A 3-level branching DAG survey uncovering specific frontend developer pain points and preferences.",
  status: "live",
  startQuestionId: "q1_react_like",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  welcomeScreen: {
    enabled: true,
    title: "React Ecosystem & Architecture Survey",
    subtitle:
      "Help us understand your experience, preferences, and architectural hurdles in the React ecosystem.",
    buttonText: "Start Survey",
    timeToComplete: "Takes 2 minutes",
  },
  nodes: {
    // Level 1 Root (4 Options)
    q1_react_like: {
      id: "q1_react_like",
      formId: "react-feedback-survey",
      questionText: "Do you like React?",
      questionType: "single_choice",
      level: 1,
      isStart: true,
      options: [
        {
          id: "opt_q1_yes",
          questionId: "q1_react_like",
          optionText: "Yes, absolutely",
          displayOrder: 1,
          nextQuestionId: "q2_yes_like_most",
        },
        {
          id: "opt_q1_neutral",
          questionId: "q1_react_like",
          optionText: "Somewhat / Neutral",
          displayOrder: 2,
          nextQuestionId: "q2_yes_like_most",
        },
        {
          id: "opt_q1_no",
          questionId: "q1_react_like",
          optionText: "No, not really",
          displayOrder: 3,
          nextQuestionId: "q2_no_why",
        },
        {
          id: "opt_q1_no_idea",
          questionId: "q1_react_like",
          optionText: "No Idea / Haven't tried it",
          displayOrder: 4,
          nextQuestionId: "q2_no_idea_why",
        },
      ],
    },

    // Level 2 Branches (4 Options Each)
    q2_yes_like_most: {
      id: "q2_yes_like_most",
      formId: "react-feedback-survey",
      questionText: "What do you like most about React?",
      questionType: "single_choice",
      level: 2,
      options: [
        {
          id: "opt_q2_comp_arch",
          questionId: "q2_yes_like_most",
          optionText: "Easy component architecture",
          displayOrder: 1,
          nextQuestionId: "q3_comp_arch_why",
        },
        {
          id: "opt_q2_fast_dev",
          questionId: "q2_yes_like_most",
          optionText: "Fast development & Hot reload",
          displayOrder: 2,
          nextQuestionId: "q3_fast_dev_why",
        },
        {
          id: "opt_q2_community",
          questionId: "q2_yes_like_most",
          optionText: "Vibrant community & packages",
          displayOrder: 3,
          nextQuestionId: "q3_community_how",
        },
        {
          id: "opt_q2_jsx_flex",
          questionId: "q2_yes_like_most",
          optionText: "JSX flexibility & Declarative UI",
          displayOrder: 4,
          nextQuestionId: "q3_comp_arch_why",
        },
      ],
    },
    q2_no_why: {
      id: "q2_no_why",
      formId: "react-feedback-survey",
      questionText: "Why don't you like React?",
      questionType: "single_choice",
      level: 2,
      options: [
        {
          id: "opt_q2_complex",
          questionId: "q2_no_why",
          optionText: "Too complex & bloated",
          displayOrder: 1,
          nextQuestionId: "q3_complex_part",
        },
        {
          id: "opt_q2_perf",
          questionId: "q2_no_why",
          optionText: "Performance & re-render issues",
          displayOrder: 2,
          nextQuestionId: "q3_perf_where",
        },
        {
          id: "opt_q2_prefer_other",
          questionId: "q2_no_why",
          optionText: "Prefer another framework (Vue/Svelte)",
          displayOrder: 3,
          nextQuestionId: "q3_other_fw",
        },
        {
          id: "opt_q2_breaking",
          questionId: "q2_no_why",
          optionText: "Frequent breaking paradigm changes",
          displayOrder: 4,
          nextQuestionId: "q3_complex_part",
        },
      ],
    },
    q2_no_idea_why: {
      id: "q2_no_idea_why",
      formId: "react-feedback-survey",
      questionText: "Why haven't you tried React?",
      questionType: "single_choice",
      level: 2,
      options: [
        {
          id: "opt_q2_no_chance",
          questionId: "q2_no_idea_why",
          optionText: "Never had a chance in projects",
          displayOrder: 1,
          nextQuestionId: "q3_current_using",
        },
        {
          id: "opt_q2_learning_other",
          questionId: "q2_no_idea_why",
          optionText: "Currently learning another framework",
          displayOrder: 2,
          nextQuestionId: "q3_learning_which",
        },
        {
          id: "opt_q2_looks_diff",
          questionId: "q2_no_idea_why",
          optionText: "Looks difficult with steep learning curve",
          displayOrder: 3,
          nextQuestionId: "q3_looks_hard_part",
        },
        {
          id: "opt_q2_happy_stack",
          questionId: "q2_no_idea_why",
          optionText: "Happy with current tech stack",
          displayOrder: 4,
          nextQuestionId: "q3_current_using",
        },
      ],
    },

    // Level 3 Details (4 Options Each)
    q3_comp_arch_why: {
      id: "q3_comp_arch_why",
      formId: "react-feedback-survey",
      questionText: "Why is component architecture useful?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_reusable",
          questionId: "q3_comp_arch_why",
          optionText: "Code reusability across projects",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_maint",
          questionId: "q3_comp_arch_why",
          optionText: "Easy maintenance & updates",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_collab",
          questionId: "q3_comp_arch_why",
          optionText: "Better team collaboration",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_modularity",
          questionId: "q3_comp_arch_why",
          optionText: "Isolated component testing & modularity",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_fast_dev_why: {
      id: "q3_fast_dev_why",
      formId: "react-feedback-survey",
      questionText: "What makes development faster for you?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_reusable_comps",
          questionId: "q3_fast_dev_why",
          optionText: "Pre-built component UI libraries",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_ecosystem",
          questionId: "q3_fast_dev_why",
          optionText: "Massive NPM ecosystem & hooks",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_hot_reload",
          questionId: "q3_fast_dev_why",
          optionText: "Instant Hot Reload & Fast Refresh",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_devtools",
          questionId: "q3_fast_dev_why",
          optionText: "Rich React DevTools & debugging",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_community_how: {
      id: "q3_community_how",
      formId: "react-feedback-survey",
      questionText: "How does the community help you most?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_tutorials",
          questionId: "q3_community_how",
          optionText: "Abundant tutorials & video guides",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_libraries",
          questionId: "q3_community_how",
          optionText: "High quality open-source packages",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_issue_res",
          questionId: "q3_community_how",
          optionText: "Quick issue resolution on forums",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_discussions",
          questionId: "q3_community_how",
          optionText: "Active Discord & Reddit communities",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_complex_part: {
      id: "q3_complex_part",
      formId: "react-feedback-survey",
      questionText: "Which part feels most difficult?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_state_mgmt",
          questionId: "q3_complex_part",
          optionText: "State management (Redux/Zustand)",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_hooks",
          questionId: "q3_complex_part",
          optionText: "Hooks rules & useEffect dependencies",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_proj_struct",
          questionId: "q3_complex_part",
          optionText: "Project structure & Vite/Webpack build",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_ssr_next",
          questionId: "q3_complex_part",
          optionText: "Server Components & Next.js SSR",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_perf_where: {
      id: "q3_perf_where",
      formId: "react-feedback-survey",
      questionText: "Where did you notice performance issues?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_large_apps",
          questionId: "q3_perf_where",
          optionText: "Large applications with deep state",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_init_load",
          questionId: "q3_perf_where",
          optionText: "Initial page loading & bundle size",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_rendering",
          questionId: "q3_perf_where",
          optionText: "Unnecessary component re-rendering",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_dom_lags",
          questionId: "q3_perf_where",
          optionText: "Heavy DOM manipulation & animations",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_other_fw: {
      id: "q3_other_fw",
      formId: "react-feedback-survey",
      questionText: "Which framework do you prefer?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_vue",
          questionId: "q3_other_fw",
          optionText: "Vue.js",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_angular",
          questionId: "q3_other_fw",
          optionText: "Angular",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_svelte",
          questionId: "q3_other_fw",
          optionText: "Svelte / SvelteKit",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_others",
          questionId: "q3_other_fw",
          optionText: "SolidJS / Astro / Plain HTML",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_current_using: {
      id: "q3_current_using",
      formId: "react-feedback-survey",
      questionText: "What are you currently using?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_html_css",
          questionId: "q3_current_using",
          optionText: "Vanilla HTML/CSS/JavaScript",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_ng_curr",
          questionId: "q3_current_using",
          optionText: "Angular Framework",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_vue_curr",
          questionId: "q3_current_using",
          optionText: "Vue.js Ecosystem",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_none_curr",
          questionId: "q3_current_using",
          optionText: "No frontend framework yet",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_learning_which: {
      id: "q3_learning_which",
      formId: "react-feedback-survey",
      questionText: "Which framework are you learning?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_ng_learn",
          questionId: "q3_learning_which",
          optionText: "Angular 18+",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_vue_learn",
          questionId: "q3_learning_which",
          optionText: "Vue 3 & Nuxt",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_svelte_learn",
          questionId: "q3_learning_which",
          optionText: "Svelte / SvelteKit",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_other_learn",
          questionId: "q3_learning_which",
          optionText: "SolidJS or Qwik",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_looks_hard_part: {
      id: "q3_looks_hard_part",
      formId: "react-feedback-survey",
      questionText: "What seems most difficult to learn?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_jsx",
          questionId: "q3_looks_hard_part",
          optionText: "JSX syntax mixing HTML & JS",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_hooks_hard",
          questionId: "q3_looks_hard_part",
          optionText: "React Hooks & State concepts",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_setup",
          questionId: "q3_looks_hard_part",
          optionText: "Initial build setup & tooling",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_everything",
          questionId: "q3_looks_hard_part",
          optionText: "Understanding components overall",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
  },
}

export const REACT_FORM_SESSIONS = [
  {
    id: "sess-react-101",
    formId: "react-feedback-survey",
    formTitle: "React Ecosystem & Developer Pain Points",
    startedAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 24 * 2 + 45000).toISOString(),
    isCompleted: true,
    pathTaken: ["q1_react_like", "q2_yes_like_most", "q3_comp_arch_why"],
    answers: [
      {
        id: "ans-r1",
        sessionId: "sess-react-101",
        questionId: "q1_react_like",
        questionText: "Do you like React?",
        optionId: "opt_q1_yes",
        optionText: "Yes, absolutely",
        answeredAt: new Date().toISOString(),
      },
      {
        id: "ans-r2",
        sessionId: "sess-react-101",
        questionId: "q2_yes_like_most",
        questionText: "What do you like most about React?",
        optionId: "opt_q2_comp_arch",
        optionText: "Easy component architecture",
        answeredAt: new Date().toISOString(),
      },
      {
        id: "ans-r3",
        sessionId: "sess-react-101",
        questionId: "q3_comp_arch_why",
        questionText: "Why is component architecture useful?",
        optionId: "opt_q3_reusable",
        optionText: "Code reusability across projects",
        answeredAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "sess-react-102",
    formId: "react-feedback-survey",
    formTitle: "React Ecosystem & Developer Pain Points",
    startedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 12 + 52000).toISOString(),
    isCompleted: true,
    pathTaken: ["q1_react_like", "q2_no_why", "q3_perf_where"],
    answers: [
      {
        id: "ans-r4",
        sessionId: "sess-react-102",
        questionId: "q1_react_like",
        questionText: "Do you like React?",
        optionId: "opt_q1_no",
        optionText: "No, not really",
        answeredAt: new Date().toISOString(),
      },
      {
        id: "ans-r5",
        sessionId: "sess-react-102",
        questionId: "q2_no_why",
        questionText: "Why don't you like React?",
        optionId: "opt_q2_perf",
        optionText: "Performance & re-render issues",
        answeredAt: new Date().toISOString(),
      },
      {
        id: "ans-r6",
        sessionId: "sess-react-102",
        questionId: "q3_perf_where",
        questionText: "Where did you notice performance issues?",
        optionId: "opt_q3_rendering",
        optionText: "Unnecessary component re-rendering",
        answeredAt: new Date().toISOString(),
      },
    ],
  },
]
