export const TYPESCRIPT_DESIGN_META = {
  id: "typescript-architecture-survey",
  name: "TypeScript Architecture & Type-Safety Survey",
  shortName: "TypeScript Architecture Survey",
  category: "Language & Architecture",
  badge: "TypeScript 5.x",
  description:
    "A 3-level branching DAG survey assessing TypeScript adoption, strictness paradigms, generics, compiler performance, and runtime validation practices.",
  theme: {
    accentColor: "#3178C6",
    badgeColor: "bg-blue-500/10 text-blue-400 border-blue-500/20",
  },
}

export const TYPESCRIPT_FORM_DESIGN = {
  id: "typescript-architecture-survey",
  title: "TypeScript Architecture & Type-Safety Insights",
  description:
    "A 3-level branching DAG survey assessing TypeScript adoption, strictness paradigms, generics, and runtime validation practices.",
  status: "live",
  startQuestionId: "q1_ts_adoption",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  welcomeScreen: {
    enabled: true,
    title: "TypeScript Architecture & Type-Safety Insights",
    subtitle:
      "Explore real-world TypeScript patterns, strict compiler flags, runtime validation, and developer experience tradeoffs.",
    buttonText: "Start Survey",
    timeToComplete: "Takes 2 minutes",
  },
  nodes: {
    // Level 1 Root (4 Options)
    q1_ts_adoption: {
      id: "q1_ts_adoption",
      formId: "typescript-architecture-survey",
      questionText: "How extensively do you use TypeScript in your projects?",
      questionType: "single_choice",
      level: 1,
      isStart: true,
      options: [
        {
          id: "opt_ts_strict",
          questionId: "q1_ts_adoption",
          optionText: "Strict TypeScript across all codebases",
          displayOrder: 1,
          nextQuestionId: "q2_strict_practices",
        },
        {
          id: "opt_ts_pragmatic",
          questionId: "q1_ts_adoption",
          optionText: "Pragmatic TypeScript (some any / loose flags)",
          displayOrder: 2,
          nextQuestionId: "q2_strict_practices",
        },
        {
          id: "opt_ts_migrating",
          questionId: "q1_ts_adoption",
          optionText: "Gradually migrating existing JavaScript projects",
          displayOrder: 3,
          nextQuestionId: "q2_migration_challenges",
        },
        {
          id: "opt_ts_js_prefer",
          questionId: "q1_ts_adoption",
          optionText: "Prefer plain JavaScript / JSDoc types",
          displayOrder: 4,
          nextQuestionId: "q2_why_no_typescript",
        },
      ],
    },

    // Level 2 Branches (4 Options Each)
    q2_strict_practices: {
      id: "q2_strict_practices",
      formId: "typescript-architecture-survey",
      questionText: "What is your primary architectural goal with TypeScript?",
      questionType: "single_choice",
      level: 2,
      options: [
        {
          id: "opt_q2_null_safety",
          questionId: "q2_strict_practices",
          optionText: "Eliminate runtime null & undefined crashes",
          displayOrder: 1,
          nextQuestionId: "q3_null_safety",
        },
        {
          id: "opt_q2_dx_autocomplete",
          questionId: "q2_strict_practices",
          optionText: "IntelliSense, auto-imports & self-documentation",
          displayOrder: 2,
          nextQuestionId: "q3_dx_tooling",
        },
        {
          id: "opt_q2_monorepo_scale",
          questionId: "q2_strict_practices",
          optionText: "Refactoring safety across large monorepos",
          displayOrder: 3,
          nextQuestionId: "q3_monorepo_scale",
        },
        {
          id: "opt_q2_domain_contracts",
          questionId: "q2_strict_practices",
          optionText: "Enforce domain data contracts & schema validation",
          displayOrder: 4,
          nextQuestionId: "q3_validation_schemas",
        },
      ],
    },
    q2_migration_challenges: {
      id: "q2_migration_challenges",
      formId: "typescript-architecture-survey",
      questionText:
        "What is the biggest hurdle during your TypeScript migration?",
      questionType: "single_choice",
      level: 2,
      options: [
        {
          id: "opt_q2_untyped_deps",
          questionId: "q2_migration_challenges",
          optionText: "Untyped 3rd-party dependencies & missing @types",
          displayOrder: 1,
          nextQuestionId: "q3_types_ecosystem",
        },
        {
          id: "opt_q2_complex_generics",
          questionId: "q2_migration_challenges",
          optionText: "Complex generics & type gymnastics errors",
          displayOrder: 2,
          nextQuestionId: "q3_complex_types",
        },
        {
          id: "opt_q2_build_slowdown",
          questionId: "q2_migration_challenges",
          optionText: "Slow typecheck & build pipeline overhead",
          displayOrder: 3,
          nextQuestionId: "q3_build_performance",
        },
        {
          id: "opt_q2_team_learning",
          questionId: "q2_migration_challenges",
          optionText: "Team learning curve & typing disputes",
          displayOrder: 4,
          nextQuestionId: "q3_team_adoption",
        },
      ],
    },
    q2_why_no_typescript: {
      id: "q2_why_no_typescript",
      formId: "typescript-architecture-survey",
      questionText: "What holds you back from adopting TypeScript fully?",
      questionType: "single_choice",
      level: 2,
      options: [
        {
          id: "opt_q2_boilerplate",
          questionId: "q2_why_no_typescript",
          optionText: "Too much typing boilerplate and ceremony",
          displayOrder: 1,
          nextQuestionId: "q3_boilerplate_friction",
        },
        {
          id: "opt_q2_js_speed",
          questionId: "q2_why_no_typescript",
          optionText: "Faster prototyping speed in plain JavaScript",
          displayOrder: 2,
          nextQuestionId: "q3_js_flexibility",
        },
        {
          id: "opt_q2_tsconfig_tooling",
          questionId: "q2_why_no_typescript",
          optionText: "Complex tsconfig, module resolution & build steps",
          displayOrder: 3,
          nextQuestionId: "q3_tooling_overhead",
        },
        {
          id: "opt_q2_jsdoc_enough",
          questionId: "q2_why_no_typescript",
          optionText: "JSDoc + TypeScript in VS Code is sufficient",
          displayOrder: 4,
          nextQuestionId: "q3_jsdoc_types",
        },
      ],
    },

    // Level 3 Details (4 Options Each)
    q3_null_safety: {
      id: "q3_null_safety",
      formId: "typescript-architecture-survey",
      questionText: "Which strict compiler flag provides the highest value?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_strict_null",
          questionId: "q3_null_safety",
          optionText: "strictNullChecks (Prevents undefined errors)",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_no_implicit_any",
          questionId: "q3_null_safety",
          optionText: "noImplicitAny (Enforces explicit signatures)",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_exact_props",
          questionId: "q3_null_safety",
          optionText: "exactOptionalPropertyTypes (Exact shape checking)",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_strict_func",
          questionId: "q3_null_safety",
          optionText: "strictFunctionTypes (Contravariant parameter checking)",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_dx_tooling: {
      id: "q3_dx_tooling",
      formId: "typescript-architecture-survey",
      questionText: "What IDE feature saves you the most time?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_symbol_rename",
          questionId: "q3_dx_tooling",
          optionText: "Reliable F2 symbol rename across full project",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_auto_import",
          questionId: "q3_dx_tooling",
          optionText: "Instant auto-import suggestions and removals",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_hover_types",
          questionId: "q3_dx_tooling",
          optionText: "Hover type inspection & inline JSDoc hints",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_param_hints",
          questionId: "q3_dx_tooling",
          optionText: "Inlay parameter hints & overload resolution",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_monorepo_scale: {
      id: "q3_monorepo_scale",
      formId: "typescript-architecture-survey",
      questionText: "How do you structure TypeScript packages in monorepos?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_ts_project_refs",
          questionId: "q3_monorepo_scale",
          optionText: "TypeScript Project References (composite tsconfig)",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_turborepo",
          questionId: "q3_monorepo_scale",
          optionText: "Turborepo / Nx with cached typecheck tasks",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_source_direct",
          questionId: "q3_monorepo_scale",
          optionText: "Direct source importing (bundler transpiles on the fly)",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_pnpm_workspaces",
          questionId: "q3_monorepo_scale",
          optionText: "pnpm workspaces with isolated prebuilt .d.ts packages",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_validation_schemas: {
      id: "q3_validation_schemas",
      formId: "typescript-architecture-survey",
      questionText:
        "Which runtime schema validation library do you pair with TS?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_zod",
          questionId: "q3_validation_schemas",
          optionText: "Zod (z.infer<typeof schema>)",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_valibot",
          questionId: "q3_validation_schemas",
          optionText: "Valibot (Lightweight modular schema validation)",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_typebox",
          questionId: "q3_validation_schemas",
          optionText: "TypeBox / AJV (JSON Schema compliance)",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_arktype",
          questionId: "q3_validation_schemas",
          optionText: "ArkType or custom type guards",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },

    q3_types_ecosystem: {
      id: "q3_types_ecosystem",
      formId: "typescript-architecture-survey",
      questionText: "How do you handle untyped legacy npm libraries?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_ambient_dts",
          questionId: "q3_types_ecosystem",
          optionText: "Write custom ambient declarations (declare module)",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_definitely_typed",
          questionId: "q3_types_ecosystem",
          optionText: "Contribute types to DefinitelyTyped (@types)",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_ts_ignore_quick",
          questionId: "q3_types_ecosystem",
          optionText: "Use @ts-expect-error as a temporary bypass",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_replace_pkg",
          questionId: "q3_types_ecosystem",
          optionText: "Replace library with modern TS-native alternative",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_complex_types: {
      id: "q3_complex_types",
      formId: "typescript-architecture-survey",
      questionText: "Which advanced TypeScript feature is most challenging?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_conditional_infer",
          questionId: "q3_complex_types",
          optionText: 'Conditional types with "infer" keywords',
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_template_literals",
          questionId: "q3_complex_types",
          optionText: "Template literal string types & pattern matching",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_mapped_types",
          questionId: "q3_complex_types",
          optionText: "Mapped types with key remapping (as [K in keyof T])",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_covariance_bivariance",
          questionId: "q3_complex_types",
          optionText: "Method bivariance vs property contravariance",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_build_performance: {
      id: "q3_build_performance",
      formId: "typescript-architecture-survey",
      questionText: "How do you optimize TypeScript build & CI performance?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_esbuild_swc",
          questionId: "q3_build_performance",
          optionText:
            "Use Vite/esbuild/SWC for strip-only transpile & tsc --noEmit in CI",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_isolated_declarations",
          questionId: "q3_build_performance",
          optionText: "Enable TypeScript 5.5+ isolatedDeclarations flag",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_ts_incremental",
          questionId: "q3_build_performance",
          optionText: "Enable tsconfig incremental & tsbuildinfo caching",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_ts_go_rust",
          questionId: "q3_build_performance",
          optionText: "Use oxc / biome / typecheck tooling runners",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_team_adoption: {
      id: "q3_team_adoption",
      formId: "typescript-architecture-survey",
      questionText: "What best accelerates team TypeScript mastery?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_strict_lints",
          questionId: "q3_team_adoption",
          optionText: "Strict typescript-eslint rule presets in CI",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_pair_programming",
          questionId: "q3_team_adoption",
          optionText: "Pair programming & type-driven design sessions",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_utility_cheatsheets",
          questionId: "q3_team_adoption",
          optionText: "Internal standard type utilities and cheatsheets",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_gradual_flags",
          questionId: "q3_team_adoption",
          optionText: "Gradually enabling compiler strict flags one by one",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },

    q3_boilerplate_friction: {
      id: "q3_boilerplate_friction",
      formId: "typescript-architecture-survey",
      questionText: "Where does typing feel most redundant?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_redux_state",
          questionId: "q3_boilerplate_friction",
          optionText: "State management actions and reducer typings",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_form_events",
          questionId: "q3_boilerplate_friction",
          optionText: "React HTML input event & ref types",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_api_responses",
          questionId: "q3_boilerplate_friction",
          optionText: "Duplicating backend DTO interfaces manually",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_generic_components",
          questionId: "q3_boilerplate_friction",
          optionText: "Polymorphic & generic UI component props",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_js_flexibility: {
      id: "q3_js_flexibility",
      formId: "typescript-architecture-survey",
      questionText:
        "What JavaScript feature do you miss most when forced to type?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_dynamic_objects",
          questionId: "q3_js_flexibility",
          optionText: "Dynamic runtime object mutations & monkey-patching",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_quick_eval",
          questionId: "q3_js_flexibility",
          optionText:
            "Running code directly in Node/browser console with zero build",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_duck_typing",
          questionId: "q3_js_flexibility",
          optionText: "Relaxed duck typing without interface ceremony",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_rapid_scripts",
          questionId: "q3_js_flexibility",
          optionText: "Quick one-off automation scripts",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_tooling_overhead: {
      id: "q3_tooling_overhead",
      formId: "typescript-architecture-survey",
      questionText: "Which configuration gives the most setup headaches?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_esm_cjs",
          questionId: "q3_tooling_overhead",
          optionText: "ESM vs CommonJS module resolution (.js imports in .ts)",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_path_aliases",
          questionId: "q3_tooling_overhead",
          optionText: "Synchronizing path aliases between tsconfig & bundler",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_dts_emit",
          questionId: "q3_tooling_overhead",
          optionText:
            "Generating and bundling production .d.ts declaration files",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_monorepo_symlinks",
          questionId: "q3_tooling_overhead",
          optionText: "Symlinks and workspace package resolution in monorepos",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
    q3_jsdoc_types: {
      id: "q3_jsdoc_types",
      formId: "typescript-architecture-survey",
      questionText:
        "What is the biggest advantage of JSDoc type checking (@checkJs)?",
      questionType: "single_choice",
      level: 3,
      options: [
        {
          id: "opt_q3_zero_compile",
          questionId: "q3_jsdoc_types",
          optionText:
            "Zero compilation step: code runs natively in Node & browsers",
          displayOrder: 1,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_clean_js",
          questionId: "q3_jsdoc_types",
          optionText:
            "Clean standard JavaScript syntax without custom superset syntax",
          displayOrder: 2,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_easy_onboarding",
          questionId: "q3_jsdoc_types",
          optionText: "Easier onboarding for beginners and JavaScript purists",
          displayOrder: 3,
          nextQuestionId: null,
        },
        {
          id: "opt_q3_ide_safety",
          questionId: "q3_jsdoc_types",
          optionText: "Full VS Code autocomplete while keeping pure JS files",
          displayOrder: 4,
          nextQuestionId: null,
        },
      ],
    },
  },
}

export const TYPESCRIPT_FORM_SESSIONS = [
  {
    id: "sess-ts-101",
    formId: "typescript-architecture-survey",
    formTitle: "TypeScript Architecture & Type-Safety Insights",
    startedAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 36 + 48000).toISOString(),
    isCompleted: true,
    pathTaken: ["q1_ts_adoption", "q2_strict_practices", "q3_null_safety"],
    answers: [
      {
        id: "ans-ts-1",
        sessionId: "sess-ts-101",
        questionId: "q1_ts_adoption",
        questionText: "How extensively do you use TypeScript in your projects?",
        optionId: "opt_ts_strict",
        optionText: "Strict TypeScript across all codebases",
        answeredAt: new Date().toISOString(),
      },
      {
        id: "ans-ts-2",
        sessionId: "sess-ts-101",
        questionId: "q2_strict_practices",
        questionText:
          "What is your primary architectural goal with TypeScript?",
        optionId: "opt_q2_null_safety",
        optionText: "Eliminate runtime null & undefined crashes",
        answeredAt: new Date().toISOString(),
      },
      {
        id: "ans-ts-3",
        sessionId: "sess-ts-101",
        questionId: "q3_null_safety",
        questionText: "Which strict compiler flag provides the highest value?",
        optionId: "opt_q3_strict_null",
        optionText: "strictNullChecks (Prevents undefined errors)",
        answeredAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "sess-ts-102",
    formId: "typescript-architecture-survey",
    formTitle: "TypeScript Architecture & Type-Safety Insights",
    startedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 18 + 59000).toISOString(),
    isCompleted: true,
    pathTaken: [
      "q1_ts_adoption",
      "q2_strict_practices",
      "q3_validation_schemas",
    ],
    answers: [
      {
        id: "ans-ts-4",
        sessionId: "sess-ts-102",
        questionId: "q1_ts_adoption",
        questionText: "How extensively do you use TypeScript in your projects?",
        optionId: "opt_ts_strict",
        optionText: "Strict TypeScript across all codebases",
        answeredAt: new Date().toISOString(),
      },
      {
        id: "ans-ts-5",
        sessionId: "sess-ts-102",
        questionId: "q2_strict_practices",
        questionText:
          "What is your primary architectural goal with TypeScript?",
        optionId: "opt_q2_domain_contracts",
        optionText: "Enforce domain data contracts & schema validation",
        answeredAt: new Date().toISOString(),
      },
      {
        id: "ans-ts-6",
        sessionId: "sess-ts-102",
        questionId: "q3_validation_schemas",
        questionText:
          "Which runtime schema validation library do you pair with TS?",
        optionId: "opt_q3_zod",
        optionText: "Zod (z.infer<typeof schema>)",
        answeredAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: "sess-ts-103",
    formId: "typescript-architecture-survey",
    formTitle: "TypeScript Architecture & Type-Safety Insights",
    startedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    completedAt: new Date(Date.now() - 3600000 * 6 + 64000).toISOString(),
    isCompleted: true,
    pathTaken: [
      "q1_ts_adoption",
      "q2_migration_challenges",
      "q3_build_performance",
    ],
    answers: [
      {
        id: "ans-ts-7",
        sessionId: "sess-ts-103",
        questionId: "q1_ts_adoption",
        questionText: "How extensively do you use TypeScript in your projects?",
        optionId: "opt_ts_migrating",
        optionText: "Gradually migrating existing JavaScript projects",
        answeredAt: new Date().toISOString(),
      },
      {
        id: "ans-ts-8",
        sessionId: "sess-ts-103",
        questionId: "q2_migration_challenges",
        questionText:
          "What is the biggest hurdle during your TypeScript migration?",
        optionId: "opt_q2_build_slowdown",
        optionText: "Slow typecheck & build pipeline overhead",
        answeredAt: new Date().toISOString(),
      },
      {
        id: "ans-ts-9",
        sessionId: "sess-ts-103",
        questionId: "q3_build_performance",
        questionText: "How do you optimize TypeScript build & CI performance?",
        optionId: "opt_q3_esbuild_swc",
        optionText:
          "Use Vite/esbuild/SWC for strip-only transpile & tsc --noEmit in CI",
        answeredAt: new Date().toISOString(),
      },
    ],
  },
]
